#base "scheme/clientscheme_colors.res"
#base "../#customizations/enabled/clientscheme_votehud.res"
#base "scheme/clientscheme_borders.res"
#base "scheme/clientscheme_settings.res"
#base "../#customizations/enabled/extendedtf2fonts.res"
#base "scheme/clientscheme_fonts.res"
#base "scheme/clientscheme_base.res" 